use std::{io::Write, num::NonZero, path::Path};

use gpu_video::{
    BytesEncoderH264, InputFrame, RawFrameData, VideoAdapter, VideoDevice, VideoInstance,
    parameters::{
        EncoderOutputParameters, EncoderParametersH264, H265Profile, RateControl,
        VideoAdapterDescriptor, VideoDeviceDescriptor, VideoInstanceDescriptor, VideoParameters,
    },
};

pub struct GpuEncoder {
    encoder: BytesEncoderH264,
    file: std::fs::File,
    width: u32,
    height: u32,
    seq: u64,
}

impl GpuEncoder {
    pub fn new(
        width: NonZero<u32>,
        height: NonZero<u32>,
        fps: f32,
        output: &Path,
    ) -> anyhow::Result<Self> {
        let instance = VideoInstance::new(&VideoInstanceDescriptor {
            enable_api_dump: false,
            enable_validations: true,
        })?;
        instance
            .iter_adapters()?
            .for_each(|a| println!("{:#?}", a.info()));
        let adapter = instance
            .create_adapter(&VideoAdapterDescriptor {
                supports_decoding: false,
                supports_encoding: true,
            })
            .unwrap();
        let device = adapter
            .create_device(&VideoDeviceDescriptor::default())
            .unwrap();

        let (num, den) = f32_to_fraction(fps, 1000);
        let mut output_params =
            device.encoder_output_parameters_h264_high_quality(RateControl::Disabled)?;
        output_params.max_references = Some(NonZero::new(1).unwrap());
        let encoder = device.create_bytes_encoder_h264(EncoderParametersH264 {
            input_parameters: VideoParameters {
                width,
                height,
                target_framerate: gpu_video::parameters::Rational {
                    numerator: num,
                    denominator: NonZero::new(den).unwrap(),
                },
            },
            output_parameters: output_params,
        })?;

        Ok(Self {
            encoder,
            file: std::fs::File::create(output)?,
            width: width.get(),
            height: height.get(),
            seq: 0,
        })
    }

    pub fn encode_frame(&mut self, frame: ndarray::Array3<u8>) -> anyhow::Result<()> {
        let (frame, _) = frame
            .as_standard_layout()
            .to_owned()
            .into_raw_vec_and_offset();

        let yuv420 = rgb2yuv420::convert_rgb_to_yuv420sp_nv12(&frame, self.width, self.height, 3);

        let bytes = self.encoder.encode(
            &InputFrame {
                data: RawFrameData {
                    frame: yuv420,
                    width: self.width,
                    height: self.height,
                },
                pts: Some(self.seq),
            },
            false,
        )?;

        self.seq += 1;
        self.file.write_all(&bytes.data)?;

        Ok(())
    }
}

impl Drop for GpuEncoder {
    fn drop(&mut self) {
        self.file.flush().unwrap();
    }
}

// Generated by Sonnet 5
fn f32_to_fraction(value: f32, max_denominator: u32) -> (u32, u32) {
    assert!(
        value.is_finite() && value >= 0.0,
        "value must be non-negative and finite"
    );

    if value == 0.0 {
        return (0, 1);
    }

    let (mut h_prev, mut h_curr): (u64, u64) = (0, 1);
    let (mut k_prev, mut k_curr): (u64, u64) = (1, 0);

    let mut x = value as f64;

    loop {
        let a = x.floor();
        let a_u = a as u64;

        let h_next = a_u * h_curr + h_prev;
        let k_next = a_u * k_curr + k_prev;

        if k_next > max_denominator as u64 {
            break;
        }

        h_prev = h_curr;
        h_curr = h_next;
        k_prev = k_curr;
        k_curr = k_next;

        let frac = x - a;
        if frac < 1e-9 {
            break; // exact (within float precision)
        }
        x = 1.0 / frac;
    }

    (h_curr as u32, k_curr as u32)
}
